src/main/java/cz/muni/fi/pa165/kodemon/entity/Gym.java
=> Gym equals and hashcode fixed + minor changes

src/test/java/cz/muni/fi/pa165/BadgeDaoTest.java
=> Badge Dao Tests added

.travis.yml, src/main/resources/META-INF/persistence.xml, src/test/java/cz/muni/fi/pa165/BadgeDaoTest.java, src/test/java/cz/muni/fi/pa165/TrainerFightDaoTest.java
Needs a look at:
Run 1: TrainerFightDaoTest.prepare:55 
Expected: is not null
but: was null
and an overall check with possible improvements.
=> TrainerFightDaoTest almost done (+fixed typo in badge dao test)

pom.xml
https://github.com/cbeust/testng/issues/1168
=> Downgrade testng.

.idea/misc.xml, persistence/src/main/java/cz/muni/fi/pa165/kodemon/dao/TrainerDao.java, persistence/src/main/java/cz/muni/fi/pa165/kodemon/entity/Trainer.java, persistence/src/test/java/cz/muni/fi/pa165/BadgeDaoTest.java, persistence/src/test/java/cz/muni/fi/pa165/GymDaoTest.java, persistence/src/test/java/cz/muni/fi/pa165/PokemonDaoTest.java, persistence/src/test/java/cz/muni/fi/pa165/SomeTest.java, persistence/src/test/java/cz/muni/fi/pa165/TrainerDaoTest.java, persistence/src/test/java/cz/muni/fi/pa165/TrainerFightDaoTest.java
Resolves #39 and #38 partially.
=> Remove id from equals() and hascode() from trainer. Add username.

service/src/main/java/com/kodemon/service/implementations/BadgeServiceImpl.java, service/src/main/java/com/kodemon/service/interfaces/BadgeService.java
=> Badge service implementation added

api/src/main/java/com/kodemon/api/dto/GymDTO.java
=> Add GymDTO

service/src/main/java/com/kodemon/service/facade/FightFacadeImpl.java, service/src/test/java/com/kodemon/service/test/facade/FightFacadeTest.java
=> Fight facade test

service/src/test/java/com/kodemon/service/test/facade/GymFacadeTest.java
=> Gym facade findall test added (working)

service/src/main/java/com/kodemon/service/facade/GymFacadeImpl.java, service/src/test/java/com/kodemon/service/test/TrainerServiceTest.java
=> Added test annotations to trainer service test + fixed a javadoc line in GymFacadeImpl

api/src/main/java/com/kodemon/api/dto/BadgeDTO.java, api/src/main/java/com/kodemon/api/dto/FightDTO.java, api/src/main/java/com/kodemon/api/dto/GymDTO.java, api/src/main/java/com/kodemon/api/dto/PokemonDTO.java, api/src/main/java/com/kodemon/api/dto/UserAuthDTO.java, api/src/main/java/com/kodemon/api/dto/UserDTO.java
=> Id added to DTOs

pom.xml, sample-data/pom.xml, sample-data/src/main/java/com/kodemon/sampledata/SampleDataConfig.java, sample-data/src/main/java/com/kodemon/sampledata/SampleDataLoadingFacade.java, sample-data/src/main/java/com/kodemon/sampledata/SampleDataLoadingFacadeImpl.java, sample-data/src/test/java/com/kodemon/sampledata/SampleDataLoadingFacadeTest.java, spring-mvc/pom.xml, spring-mvc/src/main/java/com/kodemon/springmvc/config/AppSpringMvcConfig.java
=> SampleData created

service/src/test/java/com/kodemon/service/test/TimeServiceTest.java
=> Time service test fix (+-5 miliseconds reserve added)

spring-mvc/src/main/java/com/kodemon/springmvc/config/AppSpringMvcConfig.java, spring-mvc/src/main/webapp/WEB-INF/jsp/home.jsp, spring-mvc/src/main/webapp/WEB-INF/jsp/login.jsp, spring-mvc/src/main/webapp/WEB-INF/tags/a.tag, spring-mvc/src/main/webapp/WEB-INF/tags/pagetemplate.tag
=> Created base template

persistence/src/test/java/com/kodemon/persistence/test/BadgeDaoTest.java, persistence/src/test/java/com/kodemon/persistence/test/TrainerFightDaoTest.java, service/src/main/java/com/kodemon/service/implementations/GymServiceImpl.java, service/src/test/java/com/kodemon/service/test/facade/GymFacadeTest.java
=> Dates of birth fixed to be YYYY-MM-DD and months are 0-11 instead of 1-12

sample-data/src/main/java/com/kodemon/sampledata/SampleDataConfig.java, sample-data/src/main/java/com/kodemon/sampledata/SampleDataLoadingFacadeImpl.java, sample-data/src/test/java/com/kodemon/sampledata/SampleDataLoadingFacadeTest.java, service/src/test/java/com/kodemon/service/test/TimeServiceTest.java, spring-mvc/src/main/java/com/kodemon/springmvc/config/AppSpringMvcConfig.java, spring-mvc/src/main/java/com/kodemon/springmvc/controllers/UserController.java, spring-mvc/src/main/webapp/WEB-INF/jsp/home.jsp, spring-mvc/src/main/webapp/WEB-INF/jsp/login.jsp, spring-mvc/src/main/webapp/WEB-INF/jsp/user/detail.jsp, spring-mvc/src/main/webapp/WEB-INF/jsp/user/list.jsp, spring-mvc/src/main/webapp/WEB-INF/tags/pagetemplate.tag
List of all users:
Cannot find user by username:
Incorrect username or password:
After succesful login with detail page:
=> User controller created

spring-mvc/src/main/webapp/WEB-INF/jsp/home.jsp
=> Edited home jsp with fixes and added an about part

spring-mvc/src/main/webapp/WEB-INF/jsp/gym/detail.jsp
=> Gym leaders are now clickable

api/src/main/java/com/kodemon/api/dto/BadgeDTO.java, persistence/src/main/java/com/kodemon/persistence/dao/BadgeDao.java, persistence/src/main/java/com/kodemon/persistence/entity/Badge.java, persistence/src/main/java/com/kodemon/persistence/entity/Trainer.java, persistence/src/test/java/com/kodemon/persistence/test/BadgeDaoTest.java, service/src/main/java/com/kodemon/service/facade/FightFacadeImpl.java, service/src/main/java/com/kodemon/service/facade/GymFacadeImpl.java, service/src/main/java/com/kodemon/service/facade/UserFacadeImpl.java, service/src/main/java/com/kodemon/service/implementations/BadgeServiceImpl.java, service/src/main/java/com/kodemon/service/implementations/BeanMappingServiceImpl.java, service/src/main/java/com/kodemon/service/implementations/TrainerFightServiceImpl.java, service/src/main/java/com/kodemon/service/interfaces/BadgeService.java, service/src/main/java/com/kodemon/service/interfaces/BeanMappingService.java, service/src/main/java/com/kodemon/service/interfaces/TrainerService.java, service/src/test/java/com/kodemon/service/test/BadgeServiceTest.java, service/src/test/java/com/kodemon/service/test/BeanMappingServiceTest.java, service/src/test/java/com/kodemon/service/test/TrainerServiceTest.java, service/src/test/java/com/kodemon/service/test/facade/FightFacadeTest.java, service/src/test/java/com/kodemon/service/test/facade/GymFacadeTest.java, service/src/test/java/com/kodemon/service/test/facade/UserFacadeTest.java
I (probably) fixed that bug with NPE in badge's hashcode. Needs more testing
=> Fixed transitive mapping bug in Badge/BadgeDTO

spring-mvc/src/main/webapp/WEB-INF/jsp/gym/detail.jsp
Added pokemons, removed nickname and FIGHT IT button gets disabled if the gym was already beaten.
Resolves #197 
Resolves #198 
This is how the button should look if it is disabled (this screen is fake though)
=> Gym detail improvements

spring-mvc/src/main/java/com/kodemon/springmvc/controllers/FightController.java, spring-mvc/src/main/webapp/WEB-INF/jsp/gym/detail.jsp
=> Fighting your own gym disabled, FIGHT IT button is hidden when not logged in

spring-mvc/src/main/java/com/kodemon/springmvc/controllers/FightController.java, spring-mvc/src/main/java/com/kodemon/springmvc/controllers/GymController.java, spring-mvc/src/main/java/com/kodemon/springmvc/controllers/UserController.java
=> Fixed #222. Same bug was also in the gym controller.

spring-mvc/src/main/java/com/kodemon/springmvc/controllers/FightController.java
=> Result of fighting in grass is now displayed in grass page instead of home

api/src/main/java/com/kodemon/api/dto/UserDTO.java, api/src/main/java/com/kodemon/api/facade/UserFacade.java, persistence/src/main/java/com/kodemon/persistence/entity/Trainer.java, persistence/src/main/java/com/kodemon/persistence/util/Constants.java, persistence/src/test/java/com/kodemon/persistence/test/TrainerDaoTest.java, service/src/main/java/com/kodemon/service/facade/FightFacadeImpl.java, service/src/main/java/com/kodemon/service/facade/PokemonFacadeImpl.java, service/src/main/java/com/kodemon/service/facade/UserFacadeImpl.java, service/src/main/java/com/kodemon/service/implementations/GymServiceImpl.java, service/src/main/java/com/kodemon/service/implementations/PokemonServiceImpl.java, service/src/main/java/com/kodemon/service/implementations/TrainerFightServiceImpl.java, service/src/main/java/com/kodemon/service/implementations/TrainerServiceImpl.java, service/src/main/java/com/kodemon/service/interfaces/PokemonService.java, service/src/main/java/com/kodemon/service/interfaces/TrainerService.java, service/src/test/java/com/kodemon/service/test/TrainerFightServiceTest.java, service/src/test/java/com/kodemon/service/test/facade/FightFacadeTest.java, spring-mvc/src/main/java/com/kodemon/springmvc/controllers/FightController.java, spring-mvc/src/main/java/com/kodemon/springmvc/controllers/UserController.java, spring-mvc/src/main/resources/Texts_en_US.properties, spring-mvc/src/main/resources/Texts_sk.properties, spring-mvc/src/main/webapp/WEB-INF/jsp/user/detail.jsp, spring-mvc/src/main/webapp/WEB-INF/jsp/user/reorder.jsp
=> Pokemon order switching
